#!/usr/bin/env bun
import { $ } from "bun"
import pkg from "../package.json"
import { Script } from "@anonymous-dev/0x0-script"
import { fileURLToPath } from "url"

const dir = fileURLToPath(new URL("..", import.meta.url))
process.chdir(dir)
const scope = process.env.ZEROXZERO_NPM_SCOPE ?? "@anonymous-dev"
const otp = process.env.ZEROXZERO_NPM_OTP
const npmToken = process.env.ZEROXZERO_NPM_TOKEN ?? process.env.NPM_TOKEN ?? process.env.NODE_AUTH_TOKEN

const publishTgz = async (cwd: string) => {
  const config = npmToken
    ? await Bun.write(`${cwd}/.npmrc.publish`, `//registry.npmjs.org/:_authToken=${npmToken}\n`).then(
        () => `${cwd}/.npmrc.publish`,
      )
    : undefined
  const base = `npm publish *.tgz --access public --tag ${Script.channel}${config ? ` --userconfig ${config}` : ""}`
  if (otp) {
    await $`${{ raw: `${base} --otp=${otp}` }}`.cwd(cwd)
    return
  }

  while (true) {
    const first = await $`${{ raw: base }}`.cwd(cwd).nothrow()
    if (first.exitCode === 0) return

    const stderr = first.stderr.toString()
    if (!stderr.includes("EOTP") && !stderr.includes("Access token expired or revoked")) {
      throw new Error(stderr || `npm publish failed with code ${first.exitCode}`)
    }

    if (npmToken) {
      throw new Error(stderr || "npm token auth failed")
    }

    console.log("npm requires web auth/passkey. Waiting for login...")
    const login = await $`npm login --scope=${scope} --auth-type=web`.nothrow()
    if (login.exitCode !== 0) {
      throw new Error(login.stderr.toString() || "npm login failed")
    }
  }
}

const published = async (name: string, version: string) => {
  const result = await $`npm view ${name}@${version} version`.quiet().nothrow()
  if (result.exitCode !== 0) return false
  return result.stdout.toString().trim() === version
}

const binaries: Record<string, string> = {}
const dirs: string[] = []
for (const filepath of new Bun.Glob("*/package.json").scanSync({ cwd: "./dist" })) {
  const dir = filepath.split("/")[0]
  if (!dir) continue
  const info = await Bun.file(`./dist/${filepath}`).json()
  binaries[dir] = info.version
  dirs.push(dir)
}

const version = Object.values(binaries)[0]
if (!version) throw new Error("No built binaries found in ./dist")
const scoped = Object.fromEntries(Object.entries(binaries).map(([k, v]) => [`${scope}/${k}`, v]))

for (const name of dirs) {
  const file = `./dist/${name}/package.json`
  const info = await Bun.file(file).json()
  await Bun.file(file).write(
    JSON.stringify(
      {
        ...info,
        name: `${scope}/${name}`,
      },
      null,
      2,
    ),
  )
}

await $`mkdir -p ./dist/${pkg.name}`
await $`cp -r ./bin ./dist/${pkg.name}/bin`
await $`cp ./script/postinstall.mjs ./dist/${pkg.name}/postinstall.mjs`
await Bun.file(`./dist/${pkg.name}/LICENSE`).write(await Bun.file("../../LICENSE").text())

await Bun.file(`./dist/${pkg.name}/package.json`).write(
  JSON.stringify(
    {
      name: `${scope}/${pkg.name}`,
      bin: {
        [pkg.name]: `./bin/${pkg.name}`,
      },
      scripts: {
        postinstall: "bun ./postinstall.mjs || node ./postinstall.mjs",
      },
      version: version,
      license: pkg.license,
      optionalDependencies: scoped,
    },
    null,
    2,
  ),
)

const publish = async (name: string) => {
  const full = `${scope}/${name}`
  if (await published(full, version)) {
    console.log(`skip ${full}@${version} (already published)`)
    return
  }
  if (process.platform !== "win32") {
    await $`chmod -R 755 .`.cwd(`./dist/${name}`)
  }
  await $`bun pm pack`.cwd(`./dist/${name}`)
  await publishTgz(`./dist/${name}`)
}

for (const name of dirs) {
  await publish(name)
}
const main = `${scope}/${pkg.name}`
if (await published(main, version)) {
  console.log(`skip ${main}@${version} (already published)`)
} else {
  await $`bun pm pack`.cwd(`./dist/${pkg.name}`)
  await publishTgz(`./dist/${pkg.name}`)
}

if (Script.preview) process.exit(0)

const repo = process.env.ZEROXZERO_RELEASE_REPO ?? process.env.GITHUB_REPOSITORY ?? "anonymous-dev-org/0x0"
const owner = repo.split("/")[0]
if (!owner) throw new Error(`Invalid repo: ${repo}`)
const tapRepo = process.env.ZEROXZERO_HOMEBREW_TAP || `${owner}/homebrew-tap`

const arm64Sha = await $`sha256sum ./dist/0x0-linux-arm64.tar.gz | cut -d' ' -f1`.text().then((x) => x.trim())
const x64Sha = await $`sha256sum ./dist/0x0-linux-x64.tar.gz | cut -d' ' -f1`.text().then((x) => x.trim())
const macX64Sha = await $`sha256sum ./dist/0x0-darwin-x64.zip | cut -d' ' -f1`.text().then((x) => x.trim())
const macArm64Sha = await $`sha256sum ./dist/0x0-darwin-arm64.zip | cut -d' ' -f1`.text().then((x) => x.trim())

const homebrewFormula = [
  "# typed: false",
  "# frozen_string_literal: true",
  "",
  "# This file was generated by GoReleaser. DO NOT EDIT.",
  "class Zeroxzero < Formula",
  '  desc "The AI coding agent built for the terminal."',
  `  homepage "https://github.com/${repo}"`,
  `  version "${Script.version.split("-")[0]}"`,
  "",
  '  depends_on "ripgrep"',
  "",
  "  on_macos do",
  "    if Hardware::CPU.intel?",
  `      url "https://github.com/${repo}/releases/download/v${Script.version}/0x0-darwin-x64.zip"`,
  `      sha256 "${macX64Sha}"`,
  "",
  "      def install",
  '        bin.install "zeroxzero" => "0x0"',
  "      end",
  "    end",
  "    if Hardware::CPU.arm?",
  `      url "https://github.com/${repo}/releases/download/v${Script.version}/0x0-darwin-arm64.zip"`,
  `      sha256 "${macArm64Sha}"`,
  "",
  "      def install",
  '        bin.install "zeroxzero" => "0x0"',
  "      end",
  "    end",
  "  end",
  "",
  "  on_linux do",
  "    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?",
  `      url "https://github.com/${repo}/releases/download/v${Script.version}/0x0-linux-x64.tar.gz"`,
  `      sha256 "${x64Sha}"`,
  "      def install",
  '        bin.install "zeroxzero" => "0x0"',
  "      end",
  "    end",
  "    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?",
  `      url "https://github.com/${repo}/releases/download/v${Script.version}/0x0-linux-arm64.tar.gz"`,
  `      sha256 "${arm64Sha}"`,
  "      def install",
  '        bin.install "zeroxzero" => "0x0"',
  "      end",
  "    end",
  "  end",
  "end",
  "",
].join("\n")

const githubToken = process.env.GITHUB_TOKEN
const tap = githubToken
  ? `https://x-access-token:${githubToken}@github.com/${tapRepo}.git`
  : `git@github.com:${tapRepo}.git`
await $`rm -rf ./dist/homebrew-tap`
await $`git clone ${tap} ./dist/homebrew-tap`
await $`mkdir -p ./dist/homebrew-tap/Formula ./dist/homebrew-tap/Aliases`
await Bun.file("./dist/homebrew-tap/Formula/zeroxzero.rb").write(homebrewFormula)
await $`cd ./dist/homebrew-tap && ln -sf ../Formula/zeroxzero.rb Aliases/0x0`
await $`cd ./dist/homebrew-tap && git add Formula/zeroxzero.rb Aliases/0x0`
await $`cd ./dist/homebrew-tap && git commit -m "Update to v${Script.version}"`
await $`cd ./dist/homebrew-tap && git push`
